export const industryOptions = [
  { value: "staffing_recruiting", label: "Staffing & Recruiting" },
  { value: "business_consulting", label: "Business Consulting & Services" },
  { value: "software_development", label: "Software Development" },
  {
    value: "information_technology",
    label: "Information Technology & Services",
  },
  { value: "healthcare", label: "Healthcare" },
  { value: "hospitality", label: "Hospitality" },
  { value: "finance", label: "Banking & Financial Services" },
  { value: "insurance", label: "Insurance" },
  { value: "retail", label: "Retail" },
  { value: "manufacturing", label: "Manufacturing" },
  { value: "construction", label: "Construction" },
  { value: "telecommunications", label: "Telecommunications" },
  { value: "education", label: "Education" },
  { value: "pharmaceutical", label: "Pharmaceutical" },
  { value: "biotechnology", label: "Biotechnology" },
  { value: "engineering", label: "Engineering" },
  { value: "energy", label: "Energy & Utilities" },
  { value: "transportation", label: "Transportation & Logistics" },
  { value: "real_estate", label: "Real Estate" },
  { value: "marketing_advertising", label: "Marketing & Advertising" },
  { value: "media_entertainment", label: "Media & Entertainment" },
  { value: "non_profit", label: "Non-profit Organization" },
  { value: "government", label: "Government" },
  { value: "legal", label: "Legal Services" },
  { value: "aerospace", label: "Aerospace & Defense" },
  { value: "automotive", label: "Automotive" },
  { value: "consumer_goods", label: "Consumer Goods" },
  { value: "security", label: "Security & Investigations" },
  { value: "environmental", label: "Environmental Services" },
  { value: "fitness", label: "Fitness & Wellness" },
  { value: "food_beverage", label: "Food & Beverage" },
  { value: "agriculture", label: "Agriculture" },
  { value: "mining", label: "Mining & Metals" },
  { value: "design", label: "Design" },
  { value: "human_resources", label: "Human Resources" },
  { value: "public_relations", label: "Public Relations" },
];
